/** The five things a player guesses about a location, in scoring order. */
export type TierId = 'continent' | 'country' | 'region' | 'city' | 'street';

/** Tiers whose wrong answers are baked into the manifest at build time. */
export type BakedTierId = Exclude<TierId, 'continent'>;

/**
 * How hard a location is to place, decided at build time rather than played
 * with at runtime.
 *
 * `easy` means a famous landmark is within its own visibility radius, `medium`
 * means a major city with no such landmark nearby, and `hard` is everything
 * else - including the rural panoramas that have no city worth naming close by.
 *
 * A match's difficulty setting is not the same thing as this field: hard mode
 * plays the whole pool, because "anywhere, significant or not" includes the
 * landmarks. See `filterPoolByDifficulty`.
 */
export type Difficulty = 'easy' | 'medium' | 'hard';

export interface LocationAnswer {
  continent: string;
  country: string;
  region: string;
  city: string;
  /**
   * The named road the panorama stands on, from OpenStreetMap.
   *
   * Optional in the type because manifests built before the street tier have no
   * such field, and because OSM genuinely has no name for some roads. A location
   * without one is filtered out of the pool rather than played with a short
   * ladder - see `isPlayableLocation`.
   */
  street?: string;
}

/** Four plausible wrong answers per baked tier, generated by the pool builder. */
export type LocationDistractors = Record<BakedTierId, string[]>;

export interface GameLocation {
  /** Mapillary image ID. The image URL is resolved from this at play time. */
  id: string;
  lat: number;
  lon: number;
  /** ISO date (YYYY-MM-DD) the panorama was captured. */
  capturedAt: string;
  /** Mapillary contributor username, required for CC BY-SA attribution. */
  creator: string;
  answer: LocationAnswer;
  options: LocationDistractors;

  /** Absent in manifests built before difficulty modes; treated as `hard`. */
  difficulty?: Difficulty;

  /**
   * Degrees clockwise from the panorama's own forward direction to the
   * landmark, so an easy round opens facing it.
   *
   * Deliberately relative to the image rather than to north: it is then a
   * physical fact about this panorama that no viewer convention can invalidate,
   * and the one place that knows which way a positive yaw turns is the viewer.
   */
  initialYaw?: number;

  /** The landmark this location was seeded on, named on the reveal screen. */
  landmark?: string;
}

export interface LocationManifest {
  version: string;
  generatedAt: string;
  count: number;
  locations: GameLocation[];
}
